// Assume all lyrics lines stored in a string list
// export const fetchTranslatedLyrics = async (lyrics: string[]): Promise<string[]> => {
//
// };

// mock data generated by ChatGPT
export const mockTranslatedLyrics: string[] = [
  '我们在一起的每一天',
  '即使岁月流转不再相同',
  '我依然记得那些日子',
  '你的笑容如此温暖',
  '夜空中闪烁的星光',
];
