// Assume all lyrics lines stored in a string list
// export const fetchTranslatedLyrics = async (lyrics: string[]): Promise<string[]> => {
//
// };

// mock data generated by ChatGPT
export const mockTranslatedLyrics = {
  meta: {
    title: "<song title>",
    artist: "<song artist>",
  },
  lyrics: [
    "translation test one",
    "translation test two",
    "translation test three",
    "translation test four",
    "translation test five",
  ],
};
